### ISSUE TITLE
Changeing Settings clears everything

### ISSUE THREAD

**Issue by craeckor** [BERNARDO31P/FastDownloader#1]
When you Change a Setting like the Language from English to Germany, it clears the entered URLs, the Location, where the Downloads gets saved and the Enterd URL, that want to be added to the Entered URLs and you must re enter the Stuff, that you already typed in. It's not happening, when you Change the Download Type or set it.

**Comment by BERNARDO31P** [comment]
Thank you for submitting this issue. 
I've fixed it within this commit: [Fixed loss of data when changing language](https://github.com/BERNARDO31P/FastDownloader/commit/ceaf18c25a8c62a998132598d6a6a0e72f060d73)

I hope you enjoy this application! Have a great day.

**Comment by BERNARDO31P** [comment]
Thank you for submitting this issue.
I've fixed it within those commits: 
[Fixed loss of data when changing language](https://github.com/BERNARDO31P/FastDownloader/commit/ceaf18c25a8c62a998132598d6a6a0e72f060d73)
[Fixed caching on Windows](https://github.com/BERNARDO31P/FastDownloader/commit/9c0fe032d69dcd0a937561398ea1e5c025ba1e26)

You can now update to v0.2.8-1!
I hope you enjoy this application so far! Have a great day.

**Comment by craeckor** [comment]
Thanks for fixing. it works perfectly now :)
